"""empty message

Revision ID: 2ccbd4389058
Revises: 806486351d5a
Create Date: 2019-01-19 16:22:45.703985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccbd4389058'
down_revision = '806486351d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device', ['id'])
    op.drop_column('user', 'mainowner')
    op.add_column('watering_event', sa.Column('scheduled_device', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watering_event', 'scheduled_device')
    op.add_column('user', sa.Column('mainowner', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'device', type_='unique')
    # ### end Alembic commands ###
