"""waterings

Revision ID: 794610c17d3f
Revises: 74c6f5036093
Create Date: 2019-01-14 18:41:34.448269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794610c17d3f'
down_revision = '74c6f5036093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watering_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('watering_length', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_event_timestamp'), 'watering_event', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watering_event_timestamp'), table_name='watering_event')
    op.drop_table('watering_event')
    # ### end Alembic commands ###
