"""empty message

Revision ID: bf9a6a02ae1f
Revises: 794610c17d3f
Create Date: 2019-01-19 12:48:33.170479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9a6a02ae1f'
down_revision = '794610c17d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_owner'), 'device', ['owner'], unique=True)
    op.add_column('user', sa.Column('mainowner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mainowner')
    op.drop_index(op.f('ix_device_owner'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
